server:
  port: 10001
spring:
  application:
    name: cloud-platform-admin
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  config:
    import:
      - "nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}"
#      - "nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}"