spring:
  # Redis配置（缓存中间件）
  redis:
    host: localhost
    port: 6379
    password:  # 无密码则留空
    database: 0  # 缓存数据库索引（建议与业务库区分）
    timeout: 3000ms  # 连接超时时间

  # 缓存配置（Spring Cache）
  cache:
    type: redis  # 指定缓存类型为Redis
    redis:
      time-to-live: 3600000ms  # 缓存默认过期时间（1小时）
      use-key-prefix: true     # 启用key前缀（避免不同缓存名称冲突）
      key-prefix: "cache:"     # 全局key前缀（最终key格式：cache:user:1001）
      cache-null-values: false # 不缓存null值（防止缓存穿透）