xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin  # 调度中心地址
    executor:
      appname: xxl-job-executor-demo  # 执行器名称，需与调度中心配置一致
      address: http://172.19.192.1:${server.port}/ # 执行器地址，默认为空自动注册
      ip: 172.19.192.1 # 执行器IP，默认为空自动获取
      port: ${server.port}  # 执行器端口
      logpath: /data/applogs/xxl-job/jobhandler  # 日志路径
      logretentiondays: 30  # 日志保留天数
    accessToken:  # 调度中心与执行器的通信令牌，非空时需一致